baseURL = "https://amuponda.com/"
languageCode = "en"
title = "A. Muponda"
theme = "LoveIt"

[params]
    title = "A. Muponda"
    [params.header]
        [params.header.title]
            name = "atm"

[permalinks]
    posts = '/blog/:year/:month/:day/:title/'

[markup]
    # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
    # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = true
        lineNumbersInTable = true
        # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
        # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
        noClasses = false
    # Goldmark is from Hugo 0.60 the default library used for Markdown
    # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.renderer]
            # whether to use HTML tags directly in the document
            # 是否在文档中直接使用 HTML 标签
            unsafe = true
    # Table Of Contents settings
    # 目录设置
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6